project_id = "fcyggyminzsgrlxooveu"

[functions.geminigen-image]
verify_jwt = false

[functions.geminigen-video]
verify_jwt = false

[functions.geminigen-history]
verify_jwt = false

[functions.geminigen-webhook]
verify_jwt = false
